apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role
  namespace: database
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-rolebinding
  namespace: database
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-role

