# postgresql/templates/secret.yaml
apiVersion: v1
kind: Secret # создаем объект Secret
metadata: # имя секрета
  name: postgresql-web-panel-secret # указываем, что секрет будет в database namespace
  namespace: database
type: Opaque # секрет не привязан к какому-то конкретному типу данных.
data:
  username: {{ .Values.postgresql.username | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
