apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: cache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-role
  namespace: cache
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rolebinding
  namespace: cache
subjects:
  - kind: ServiceAccount
    name: redis-sa
    namespace: cache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-role
