# redis/templates/secret.yaml
apiVersion: v1
kind: Secret # создаем объект Secret
metadata: # имя секрета
  name: redis-web-panel-secret # указываем, что секрет будет в cache namespace
  namespace: cache
type: Opaque # секрет не привязан к какому-то конкретному типу данных.
data:
  password: {{ .Values.redis.password | b64enc }}
