# redis/templates/service.yaml
# 🔹 Service для Primary (запись)
apiVersion: v1
kind: Service
metadata:
  name: redis-web-panel-master
  namespace: cache
spec:
  type: ClusterIP
  selector:
    app: redis-web-panel
    role: master
  ports:
    - protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}

---

# 🔹 Service для Read Replicas (чтение)
apiVersion: v1
kind: Service
metadata:
  name: redis-web-panel-read
  namespace: cache
spec:
  type: ClusterIP
  selector:
    app: redis-web-panel
    role: replica
  ports:
    - protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
