user_queries:
  get_user_by_login: >
    SELECT 
    u.login, 
    u.password_hash, 
    r.role_name AS role_name 
    FROM users u
    JOIN
      role r ON u.role_id = r.id
    WHERE 
      u.login = :login
    
  get_user_with_role_and_permissions: >
    SELECT 
      u.id AS user_id,
      u.login,
      r.role_name,
      r.description AS role_description,
      ARRAY_AGG(p.name) AS permissions_names,
      ARRAY_AGG(p.description) AS permissions_descriptions
    FROM 
      users u
    JOIN 
      role r ON u.role_id = r.id
    LEFT JOIN 
      role_permission rp ON rp.role_id = r.id
    LEFT JOIN 
      permission p ON rp.permission_id = p.id
    WHERE 
      u.login = :login AND u.password_hash = :password_hash
    GROUP BY 
      u.id, u.login, r.role_name, r.description

role_queries:

  get_all_roles_and_permissions: >
    SELECT 
      r.id AS role_id,
      r.role_name,
      ARRAY_AGG(p.name) AS permission_names
    FROM 
      role r
    LEFT JOIN
      role_permission rp ON r.id = rp.role_id
    LEFT JOIN
      permission p ON rp.permission_id = p.id
    GROUP BY
      r.id, r.role_name