# app/values.yaml
flaskApp:
  image: "flask-web-panel"
  tag: "dev"
  pullPolicy: "IfNotPresent" # Политика pull для образа
  servicePort: 8000

  project_root: "/app"
  allure_host: ""
  project_id: "web-panel"
  send_path: "/allure-docker-service/send-results"
  generate_path: "/allure-docker-service/generate-report"
  flask_app: "src/app/run.py"
  flask_status_debug: "true"
  flask_status_testing: "true"
  flask_status_prod_stages: "false"
  flask_wtf_csrf_enabled: "false"
  flask_config_path: "config/app_config.toml"
  flask_secret_key_session: "web_panel_user"
  flask_secret_key_fallbacks: "web_panel_password"
  database_uri: "postgresql://web_panel_user:web_panel_password@postgresql-web-panel-primary.database:5432/web_panel_panel_db"
  redis_uri: "redis://:@redis-web-panel-master.cache:6379/0"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  host: web.local
  path: /
  pathType: Prefix

rbac:
  create: true
  serviceAccountName: flask-app-web-panel