# app/templates/ingress-app.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restricted-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
    - host: web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-web-panel
                port:
                  number: 8000